version: "3.8"

services:
  msa_front:
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    image: ubiqube/msa2-front:58c95188ecf920dc3a42d243cfcba79c004fc2c4
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host
    volumes:
        - "msa_front:/etc/nginx/ssl"

  camunda:
    image: camunda/camunda-bpm-platform:7.13.0

  db:
    image: ubiqube/msa2-db:0fa25b25ce930c2da8d73d14e0fa11dab06207d7
    command: postgres -c 'max_connections=800'
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "msa_db:/var/lib/postgresql/data"

  msa_api:
    depends_on:
      - db
      - msa_es
    image: ubiqube/msa2-api:77c1751e3a498453286d6ffbf3120eecc83e475c
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "rrd_repository:/opt/rrd"
      - "msa_dev:/opt/devops/"
      - "msa_api_logs:/opt/jboss/wildfly/standalone/log"
      - "msa_api_logs:/opt/wildfly/logs/processLog"

  msa_ui:
    depends_on:
      - msa_api
    image: ubiqube/msa2-ui:255d026ece4bc2cc10d7af91071129b36408a6c3
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true
    - FEATURE_TOPOLOGY=true
    - FEATURE_MONITORING_PROFILES=true

  msa_es:
    image: ubiqube/msa2-es:037a2067826b36e646b45e5a148431346f62f3a6
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
      - bootstrap.memory_lock=true
    volumes:
      - "msa_es:/usr/share/elasticsearch/data"

  msa_sms:
    image: ubiqube/msa2-sms:0107cbf1ac1f1d2067c69a76b107e93f9de9cbd7
    depends_on:
      - db
      - msa_es
      - msa_dev
    volumes:
      - "msa_dev:/opt/devops/"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "rrd_repository:/opt/rrd"
      - "msa_sms_logs:/opt/sms/logs"
    ports:
      - "69:69"

  msa_bud:
    depends_on:
      - db
    image: ubiqube/msa2-bud:43ee454c22b9ed217dac6baba9a88a345a5422c2
    volumes:
      - "msa_bud_logs:/opt/bud/logs/"

  msa_cerebro:
    image: lmenezes/cerebro:0.9.2
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"

  msa_dev:
    # uncomment to use a local image for quickstart dev 
    build: ./lab/msa_dev
    #image: ubiqube/msa2-linuxdev:0673683b389103f2ccf72731d7cfde562854d679
    depends_on:
      - msa_es
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_dev:/opt/devops/"

  linux_me:
    # use local image for quickstart dev => for release: make sure the chnages are ported to msa-docker and uncomment the line below
    #image: ubiqube/msa2-linuxme
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
      - sys_rawio
    ports:
      - "2224:22"
    devices:                     # required for dmidecode used by polld/asset
      - "/dev/mem:/dev/mem"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me

volumes:
  msa_api:
  msa_db:
  msa_dev:
  msa_entities:
  msa_repository:
  msa_es:
  rrd_repository:
  msa_api_logs:
  msa_sms_logs:
  msa_bud_logs:
  msa_front:

networks:
  default:
    name: quickstart_default
    ipam:
      config:
        - subnet: 172.20.0.0/24

