version: "3.8"

services:
  msa_front:
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    image: ubiqube/msa2-front:8b5667ce73bc80d99b6f6180ae2f27a6877537f1
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host

  camunda:
    image: camunda/camunda-bpm-platform

  db:
    image: ubiqube/msa2-db:2b7c486764c882abe1a720094ec5159d3bd75389
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "msa_db:/var/lib/postgresql/data"
      
  msa_api:
    image: ubiqube/msa-api:ab3b36dd0d06e73ceec498cea47c469e7b025f9f
    depends_on:
      - db
      - msa_es
      - msa_dev
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    ports:
      - "8480:8480"
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "rrd_repository:/opt/rrd"

  msa_ui:
    depends_on:
      - msa_api
    image: ubiqube/msa2-ui:840a775086418898f1f8a01c5e02468d7cc9a2d0
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true

  msa_es:
    image: ubiqube/msa2:es-2.1
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
      - bootstrap.memory_lock=true
    volumes: 
      - "msa_es:/usr/share/elasticsearch/config"
      - "msa_es:/usr/share/elasticsearch/data"
      - "msa_es:/etc/elasticsearch"

  msa_sms:
    build: ./lab/msa_sms
    depends_on:
      - db
      - msa_es
      - msa_dev
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_sms:/opt/sms/bin/php"
      - "msa_config:/opt/configurator"
      - "msa_dev:/opt/devops/"
      - "msa_sms:/opt/sms/devices"
      - "rrd_repository:/opt/rrd"
    privileged: true

  msa_bud:
    depends_on:
      - db
    image: ubiqube/msa2-bud:5e55e804fc5eb647a9258c743d7eacf93e33decb
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true


  msa_cerebro:
    image: lmenezes/cerebro
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es_link:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"

  msa_dev:
    build: ./lab/msa_dev
    depends_on:
      - msa_es
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_sms:/opt/sms/bin/php"
      - "msa_sms:/opt/sms/devices"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_config:/opt/configurator"
      - "msa_dev:/opt/devops/"
      - "msa_es:/usr/share/elasticsearch/config"
      - "msa_es:/etc/elasticsearch"

  linux_me:
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
    ports:
      - "2224:22"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me
  
volumes:
  msa_db:
  msa_entities:
  msa_repository:
  msa_sms:
  msa_api:
  msa_config:
  msa_dev:
  rrd_repository:
  msa_es:

networks:
  default:
    name: quickstart_default
    ipam:
      config:
        - subnet: 172.20.0.0/24

