version: "3.8"

services:
  msa_front:
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    image: ubiqube/msa2-front:319bd74db43185cd6456563c55bc0cdf9c4eff37
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host

  camunda:
    image: camunda/camunda-bpm-platform
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

  msa_ui:
    depends_on:
      - msa_api
    image: ubiqube/msa2-ui:d5ef0bc036cccec555247711408536a149334ba9
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true

  db:
    image: ubiqube/msa2-db:2b7c486764c882abe1a720094ec5159d3bd75389
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "/mnt/NASVolume/msa_db:/var/lib/postgresql/data"
    deploy:
      replicas: 1

  msa_api:
    depends_on:
      - db
    image: ubiqube/msa-api:b0e07f0b076e8a6da3ee094a0aeff20c5021f2ae
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "/mnt/NASVolume/rrd_repository:/opt/rrd"
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"

  msa_sms:
    depends_on:
      - db
    image: ubiqube/msa2-sms:feefa4f1f72a0c28d8f01aaa455ec2f834becbed
    volumes:
      - "/mnt/NASVolume/rrd_repository:/opt/rrd"
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

  msa_bud:
    depends_on:
      - db
    image: ubiqube/msa2-bud:26cf8835dadb548dd8c23edc8b7d671c1489d10b
    deploy:
      replicas: 1

  msa_linux:
    image: ubiqube/msa2-linuxme

  msa_es:
    image: ubiqube/msa2-es:2.1GA
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
    volumes:
      - "/mnt/NASVolume/msa_es:/usr/share/elasticsearch/data"

  msa_dev:
    image: ubiqube/msa2-linuxdev
    depends_on:
      - msa_es
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
    volumes:
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"
      - "/mnt/NASVolume/msa_sms_php:/opt/sms/bin/php"
      - "/mnt/NASVolume/msa_sms_devices:/opt/sms/devices"
      - "/mnt/NASVolume/msa_api:/opt/ubi-jentreprise/generated/conf"
      - "/mnt/NASVolume/msa_config:/opt/configurator"
      - "/mnt/NASVolume/msa_dev:/opt/devops/"

