version: "3.8"

services:
  msa_front:
    depends_on:
      - msa_api
      - msa_ui
      - camunda
      - msa_sms
    image: ubiqube/msa2-front:96ee3ae7a03985d80e337238dadc575544e1cec3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host

  camunda:
    image: camunda/camunda-bpm-platform

  db:
    image: ubiqube/msa2-db:2b7c486764c882abe1a720094ec5159d3bd75389
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "msa_db:/var/lib/postgresql/data"

  msa_api:
    image: ubiqube/msa-api:80b9b59ff7c812b188233ba4bc91cca68e4648b6
    depends_on:
      - db
      - msa_es
      - msa_dev
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "rrd_repository:/opt/rrd"

  msa_ui:
    depends_on:
      - msa_api
    image: ubiqube/msa2-ui:0514c1c9991bf0d0e1cbaf87e419d65a7ea97b62
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true
    - FEATURE_TOPOLOGY=true


  msa_es:
    image: ubiqube/msa2-es:037a2067826b36e646b45e5a148431346f62f3a6
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
      - bootstrap.memory_lock=true
    volumes:
      - "msa_es:/usr/share/elasticsearch/data"

  msa_sms:
    image: ubiqube/msa2-sms:e8c49d8a6616565870a92bf27fddde8db5db228a
    depends_on:
      - db
      - msa_es
      - msa_dev
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_sms_php:/opt/sms/bin/php"
      - "msa_config:/opt/configurator"
      - "msa_dev:/opt/devops/"
      - "msa_sms_devices:/opt/sms/devices"
      - "rrd_repository:/opt/rrd"

  msa_bud:
    depends_on:
      - db
    image: ubiqube/msa2-bud:26cf8835dadb548dd8c23edc8b7d671c1489d10b
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"


  msa_cerebro:
    image: lmenezes/cerebro
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"

  msa_dev:
    # use local image for quickstart dev => for release: make sure the chnages are ported to msa-docker and uncomment the line below
    #image: ubiqube/msa2-linuxdev
    build: ./lab/msa_dev
    depends_on:
      - msa_es
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_sms_php:/opt/sms/bin/php"
      - "msa_sms_devices:/opt/sms/devices"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_config:/opt/configurator"
      - "msa_dev:/opt/devops/"

  linux_me:
    # use local image for quickstart dev => for release: make sure the chnages are ported to msa-docker and uncomment the line below
    #image: ubiqube/msa2-linuxme
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
      - sys_rawio
    ports:
      - "2224:22"
    devices:                     # required for dmidecode used by polld/asset
      - "/dev/mem:/dev/mem"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me

volumes:
  msa_db:
  msa_entities:
  msa_repository:
  msa_sms_php:
  msa_sms_devices:
  msa_api:
  msa_config:
  msa_dev:
  rrd_repository:
  msa_es:

networks:
  default:
    name: quickstart_default
    ipam:
      config:
        - subnet: 172.20.0.0/24

