version: "3.8"

services:
  msa_front:
    depends_on:
      - msa_api
      - msa_ui
      - camunda
      - msa_sms
    image: ubiqube/msa2-front:0203e1bdf67817e89bee08fb1f8ca62319053cfe
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host

  camunda:
    image: camunda/camunda-bpm-platform

  db:
    image: ubiqube/msa2-db:2b7c486764c882abe1a720094ec5159d3bd75389
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "msa_db:/var/lib/postgresql/data"
      
  msa_api:
    image: ubiqube/msa-api:b58bf7c59f1f683b49cd55735e612f9bf3da212b
    depends_on:
      - db
      - msa_es
      - msa_dev
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "rrd_repository:/opt/rrd"

  msa_ui:
    depends_on:
      - msa_api
    image: ubiqube/msa2-ui:7cd08dcbab185ff1c557db549674411963aba1b4
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true

  msa_es:
    image: ubiqube/msa2:es-2.1
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
      - bootstrap.memory_lock=true
    volumes:
      - "msa_es:/usr/share/elasticsearch/data"

  msa_sms:
    build: ./lab/msa_sms
    depends_on:
      - db
      - msa_es
      - msa_dev
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_sms:/opt/sms/bin/php"
      - "msa_config:/opt/configurator"
      - "msa_dev:/opt/devops/"
      - "msa_sms:/opt/sms/devices"
      - "rrd_repository:/opt/rrd"

  msa_bud:
    depends_on:
      - db
    image: ubiqube/msa2-bud:42951df0800592a00a651717ab4a13573562e63c
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"


  msa_cerebro:
    image: lmenezes/cerebro
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"

  msa_dev:
    build: ./lab/msa_dev
    depends_on:
      - msa_es
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_sms:/opt/sms/bin/php"
      - "msa_sms:/opt/sms/devices"
      - "msa_api:/opt/ubi-jentreprise/generated/conf"
      - "msa_config:/opt/configurator"
      - "msa_dev:/opt/devops/"
      - "msa_es:/usr/share/elasticsearch/config"
      - "msa_es:/etc/elasticsearch"

  linux_me:
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
    ports:
      - "2224:22"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me
  
volumes:
  msa_db:
  msa_entities:
  msa_repository:
  msa_sms:
  msa_api:
  msa_config:
  msa_dev:
  rrd_repository:
  msa_es:

networks:
  default:
    name: quickstart_default
    ipam:
      config:
        - subnet: 172.20.0.0/24

