version: "3.8"

services:
  msa_front:
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    image: ubiqube/msa2-front:009bf0a92ed5f06727a7e08687ab1ad2c43a3213
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host

  camunda:
    image: camunda/camunda-bpm-platform

  db:
    image: ubiqube/msa2-db:2b7c486764c882abe1a720094ec5159d3bd75389
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "msa_db:/var/lib/postgresql/data"

  msa_api:
    image: ubiqube/msa-api:81bf40b259d46d5e8eccfaf7f2829c6e8d675c64
    depends_on:
      - db
      - msa_es
      - msa_dev
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    ports:
      - "8480:8480"
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_api:/opt/ubi-jentreprise/resources/templates"

  msa_ui:
    depends_on:
      - msa_api
    image: ubiqube/msa2-ui:6a31c60ecd079b805407b6cffb6a70eee2ea36eb
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true

  msa_es:
    image: elasticsearch:7.2.1
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"

  msa_sms:
    build: ./lab/msa_sms
    depends_on:
      - db
      - msa_es
      - msa_dev
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_sms:/opt/sms/bin/php"
      - "msa_sms:/opt/sms/templates"
      - "msa_config:/opt/configurator"
      - "msa_dev:/opt/devops/"
    privileged: true

  msa_bud:
    depends_on:
      - db
    image: ubiqube/msa2-bud:9c28dd1e3b47a52994533c7cd3a5171c340a4a44
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true


  msa_cerebro:
    image: lmenezes/cerebro
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es_link:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"

  msa_dev:
    build: 
      context: ./lab/msa_dev
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"
      - "msa_sms:/opt/sms/bin/php"
      - "msa_sms:/opt/sms/devices"
      - "msa_api:/opt/ubi-jentreprise/resources/templates"
      - "msa_config:/opt/configurator"
      - "msa_dev:/opt/devops/"

    privileged: true

  linux_me:
    image: linux:me
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
    ports:
      - "2224:22"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me
  
volumes:
  msa_db:
  msa_entities:
  msa_repository:
  msa_sms:
  msa_api:
  msa_config:
  msa_dev:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24

