# This docker-compose file is provided as an exmaple to create a Docker Swarm based MSActivator setup
version: "3.8"

services:
  msa_front:
    image: ubiqube/msa2-front:893baa9b939919711d6414ba1f651820b744e4b7
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host
    volumes:
      - "/mnt/NASVolume/msa_front:/etc/nginx/ssl"

  db:
    image: ubiqube/msa2-db:7ded9624984d2af7dae97518a8780ccca953e7f1
    command: postgres -c 'max_connections=800'
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "/mnt/NASVolume/msa_db:/var/lib/postgresql/data"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  msa_api:
    image: ubiqube/msa2-api:d3bf6e61bfea9dd662a721248ecdba00f43fcfea
    depends_on:
      - db
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "/mnt/NASVolume/msa_api:/opt/ubi-jentreprise/generated/conf"
      - "/mnt/NASVolume/rrd_repository:/opt/rrd"
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"

  msa_ui:
    image: ubiqube/msa2-ui:5c75626e0820ba2ca9a7aa867515fc35fccffbb8
    depends_on:
      - msa_api
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true
    - FEATURE_TOPOLOGY=true
    - FEATURE_MONITORING_PROFILES=true

  msa_sms:
    image: ubiqube/msa2-sms:05c28160213d0f16de882b0503e4e73572f9908c
    depends_on:
      - db
    volumes:
      - "/mnt/NASVolume/msa_dev:/opt/devops/"
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"
      - "/mnt/NASVolume/rrd_repository:/opt/rrd"
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

  msa_bud:
    image: ubiqube/msa2-bud:ae2819b776e5d60920ba5b1b5f6f510bb6e50f6c
    depends_on:
      - db
    deploy:
      replicas: 1

  camunda:
    image: camunda/camunda-bpm-platform:7.13.0
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1

  msa_es:
    image: ubiqube/msa2-es:037a2067826b36e646b45e5a148431346f62f3a6
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
    volumes:
      - "/mnt/NASVolume/msa_es:/usr/share/elasticsearch/data"

  msa_kibana:
    image: ubiqube/msa2-kibana:5634d2ada524a9dab10711637fb76c4570424501
    ports:
      - "5601:5601"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

  msa_cerebro:
    image: lmenezes/cerebro:0.9.2
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

  msa_dev:
    image: ubiqube/msa2-linuxdev:e4087c9947273aa71e762247ed36c5d6309f3a64
    depends_on:
      - msa_es
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"
      - "/mnt/NASVolume/msa_api:/opt/ubi-jentreprise/generated/conf"
      - "/mnt/NASVolume/msa_dev:/opt/devops/"

  msa_linux:
    image: ubiqube/msa2-linuxme:7fc20ffaef77c39f402b6fcaa81b24540ee35850