version: "3.7"

services:
  msa_front:
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    image: ubiqube/msa2-front:74e52c480d40d29f4b9f6d92c7a0271c55e13900
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host

  camunda:
    image: camunda/camunda-bpm-platform

  db:
    image: ubiqube/msa2-db:2d85a6d93725e546555c92a68f1194a044813c82
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "msa_db:/var/lib/postgresql/data"

  msa_api:
    depends_on:
      - db
      - msa_es
    image: ubiqube/msa-api:660e15a7bf4df3736d2e620d0a52064ab10d1754
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    ports:
      - "8480:8480"
    volumes:
      - "msa_entities:/opt/fmc_entities"
      - "msa_repository:/opt/fmc_repository"

  msa_ui:
    depends_on:
      - msa_api
    image: ubiqube/msa2-ui:a6e2841638ecbe799ade5bead485212fe9c5607c
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true

  msa_es:
    image: elasticsearch:7.2.1
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"

  msa_sms:
    depends_on:
      - db
      - msa_es
    image: ubiqube/msa2-sms:9f9f30ff2ee6320e0bcf8badc94f1b0fba70b3d7
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true

  msa_bud:
    depends_on:
      - db
    image: ubiqube/msa2-bud:afb789f49b377e4a0f90394f485c6d4047c57afd
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    privileged: true


  msa_cerebro:
    image: lmenezes/cerebro
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es_link:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"

  linux_me:
    image: linux:me
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
    ports:
      - "2224:22"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me
  
volumes:
  msa_db:
  msa_entities:
  msa_repository:

networks:
  default:
    ipam:
      config:
        - subnet: 172.20.0.0/24
