# This docker-compose file is provided as an exmaple to create a Docker Swarm based MSActivator setup
version: "3.8"

services:
  msa_front:
    image: ubiqube/msa2-front:ee5d100177fc755da2e2117b9a6f6bafed023e59
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host
    #
    # uncomment one of the 2 section below when installing a custom certificate 
    # - Docker standard standalone installation
    #volumes:
    #    - "msa_front:/etc/nginx/ssl"
    # - Docker Swarm HA installation
    #volumes:
    #    - "/mnt/NASVolume/msa_front:/etc/nginx/ssl"

  db:
    image: ubiqube/msa2-db:42961a9928f0f2949309965322e991e0c00b87b1
    command: postgres -c 'max_connections=800'
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "/mnt/NASVolume/msa_db:/var/lib/postgresql/data"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  msa_api:
    image: ubiqube/msa2-api:06d72e87177a87f62d89183e09c831bce31935cf
    depends_on:
      - db
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "/mnt/NASVolume/msa_dev:/opt/devops/"
      - "/mnt/NASVolume/rrd_repository:/opt/rrd"
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"

  msa_ui:
    image: ubiqube/msa2-ui:a395460e1b97bb6fdee0ba65ac229354602c3ff7
    depends_on:
      - msa_api
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true
    - FEATURE_TOPOLOGY=true
    - FEATURE_MONITORING_PROFILES=true

  msa_sms:
    image: ubiqube/msa2-sms:74a31cc3b2acb6601d78966aaa1b1d61962a1267
    depends_on:
      - db
    volumes:
      - "/mnt/NASVolume/msa_dev:/opt/devops/"
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"
      - "/mnt/NASVolume/rrd_repository:/opt/rrd"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  msa_bud:
    image: ubiqube/msa2-bud:a621aedde7f3a311f84eaf2c886506c2899d9551
    depends_on:
      - db
    deploy:
      replicas: 1

  camunda:
    image: camunda/camunda-bpm-platform:7.13.0
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  msa_es:
    image: ubiqube/msa2-es:d9899d1f09809a40548f96211984647a8b4901fc
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
    #volumes:
    #  - "/mnt/NASVolume/msa_es:/usr/share/elasticsearch/data"

  msa_dev:
    image: ubiqube/msa2-linuxdev:e4087c9947273aa71e762247ed36c5d6309f3a64
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
    volumes:
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"
      - "/mnt/NASVolume/msa_api:/opt/ubi-jentreprise/generated/conf"
      - "/mnt/NASVolume/msa_dev:/opt/devops/"

  msa_linux:
    image: ubiqube/msa2-linuxme:7fc20ffaef77c39f402b6fcaa81b24540ee35850
