# This docker-compose file is provided as an exmaple to create a Docker Swarm based MSActivator setup
version: "3.8"

services:
  msa_front:
    depends_on:
      - msa_api
      - msa_ui
      - camunda
    image: ubiqube/msa2-front:79f992043bcab882b33718822977201fe27f90c5
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 514
        published: 514
        protocol: udp
        mode: host
    volumes:
      - "/mnt/NASVolume/msa_front:/etc/nginx/ssl"

  camunda:
    image: camunda/camunda-bpm-platform:7.13.0
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  db:
    image: ubiqube/msa2-db:7ded9624984d2af7dae97518a8780ccca953e7f1
    command: postgres -c 'max_connections=800'
    environment:
      POSTGRES_PASSWORD: my_db_password
      POSTGRES_DB: POSTGRESQL
    volumes:
      - "/mnt/NASVolume/msa_db:/var/lib/postgresql/data"
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"

  msa_api:
    depends_on:
      - db
    image: ubiqube/msa2-api:98e27bc3c38486466d41041e2e5afbd314467a55
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
    entrypoint:
      - /opt/jboss/wildfly/bin/standalone.sh
      - -b
      - 0.0.0.0
      - -bmanagement
      - 0.0.0.0
      - -c
      - ubiqube.xml
    volumes:
      - "/mnt/NASVolume/msa_api:/opt/ubi-jentreprise/generated/conf"
      - "/mnt/NASVolume/rrd_repository:/opt/rrd"
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"

  msa_ui:
    depends_on:
      - msa_api
    image: ubiqube/msa2-ui:7a1b18286a257e38ecb271120e9d867ae1184422
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
    - FEATURE_ADMIN=true
    - FEATURE_CONNECTION_STATUS=true
    - FEATURE_ALARMS=true
    - FEATURE_LICENCE=true
    - FEATURE_TOPOLOGY=true

  msa_sms:
    depends_on:
      - db
    image: ubiqube/msa2-sms:0c35674640403a0bb8912d83828298bd02d1cbbb
    volumes:
      - "/mnt/NASVolume/msa_dev:/opt/devops/"
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"
      - "/mnt/NASVolume/rrd_repository:/opt/rrd"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1

  msa_bud:
    depends_on:
      - db
    image: ubiqube/msa2-bud:b23dbf64520fbddbc74ab6468bd23cf9b8ee3393
    deploy:
      replicas: 1

  msa_es:
    image: ubiqube/msa2-es:037a2067826b36e646b45e5a148431346f62f3a6
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      - "discovery.type=single-node"
      - "script.painless.regex.enabled=true"
    volumes:
      - "/mnt/NASVolume/msa_es:/usr/share/elasticsearch/data"

  msa_cerebro:
    image: lmenezes/cerebro:0.9.2
    entrypoint:
      - /opt/cerebro/bin/cerebro
      - -Dhosts.0.host=http://msa_es:9200
    depends_on:
      - msa_es
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - "node.role==manager"

  msa_dev:
    # uncomment to use a local image for quickstart dev 
    build: ./lab/msa_dev
    #image: ubiqube/msa2-linuxdev:0673683b389103f2ccf72731d7cfde562854d679
    depends_on:
      - msa_es
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
    volumes:
      - "/mnt/NASVolume/msa_entities:/opt/fmc_entities"
      - "/mnt/NASVolume/msa_repository:/opt/fmc_repository"
      - "/mnt/NASVolume/msa_api:/opt/ubi-jentreprise/generated/conf"
      - "/mnt/NASVolume/msa_dev:/opt/devops/"

  linux_me:
    # use local image for quickstart dev => for release: make sure the chnages are ported to msa-docker and uncomment the line below
    #image: ubiqube/msa2-linuxme
    build: ./lab/linux.me
    cap_add:
      - NET_ADMIN
      - sys_rawio
    ports:
      - "2224:22"
    devices:                     # required for dmidecode used by polld/asset
      - "/dev/mem:/dev/mem"
    networks:
      default:
        ipv4_address: 172.20.0.101
    hostname: linux_me
