name: "msa_custom"
tags: ["msa_custom", "private_instance"]
filebeat.inputs:
- type: log
  paths:
    - '/var/lib/docker/volumes/quickstart_msa_sms_logs/_data/*.log'
  multiline:
    type: pattern
    pattern: ^[0-9]{4}\/[0-9]{2}\/([0-9]{2}\:){3}[0-9]{2}
    negate: true
    match: after
output.elasticsearch:
  hosts: "msa_es:9200"
  username: "elastic"
  password: "PASSWORD HERE"
  protocol: "https"
  ssl.verification_mode: none
  indices:
    - index: "msa-sms-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.contains:
        log.file.path: "quickstart_msa_sms_logs"
setup.kibana:
  host: "msa_kibana:5601"
  protocol: "https"
  ssl.verification_mode: none
  username: "elastic"
  password: "PASSWORD HERE"